'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { analyzeExhibitImage, type AnalyzeExhibitImageOutput } from '@/ai/flows/analyze-exhibit-image';
import { updateExhibitImage } from '@/ai/flows/update-exhibit-image';
import { chatAboutExhibitContext } from '@/ai/flows/chat-about-exhibit-context';
import { addExhibitItem, deleteExhibitItem, getExhibitItemById, updateExhibitItem } from './data';
import type { ChatMessage, ExhibitItem, ExhibitMetadata } from './types';
import { getStorage } from 'firebase-admin/storage';
import { getFirebaseAdminApp } from '@/firebase/admin';

async function uploadImageToStorage(photoDataUri: string, itemId: string, imageIndex: number): Promise<string> {
    getFirebaseAdminApp(); // Ensure admin app is initialized
    const bucket = getStorage().bucket();
    const extension = photoDataUri.split(';')[0].split('/')[1];
    const fileName = `exhibits/${itemId}/image_${imageIndex}.${extension}`;
    const file = bucket.file(fileName);
    
    const buffer = Buffer.from(photoDataUri.replace(/^data:image\/\w+;base64,/, ""), 'base64');
    
    await file.save(buffer, {
        metadata: {
            contentType: `image/${extension}`,
        },
    });

    // Make the file public and get the URL
    await file.makePublic();
    return file.publicUrl();
}


export async function analyzeImageAction(formData: FormData): Promise<{ error?: string, newItemId?: string }> {
  const photoDataUri = formData.get('image-data-uri') as string;
  const name = formData.get('name') as string;
  const description = formData.get('description') as string;

  if (!photoDataUri) {
    return { error: 'No image data provided.' };
  }

  try {
    const analysisResult: AnalyzeExhibitImageOutput = await analyzeExhibitImage({ photoDataUri, description });

    const finalName = name || analysisResult.metadata.name || 'Untitled Artifact';
    const finalDescription = description || analysisResult.metadata.description || 'No description provided.';
    
    // This item is missing the ID, which will be generated by Firestore.
    // It is also missing the image URL, which we'll add after creation.
    const newItemData: Omit<ExhibitItem, 'id' | 'images' | 'createdAt'> = {
      name: finalName,
      description: finalDescription,
      metadata: {
        ...analysisResult.metadata,
        name: finalName,
        description: finalDescription,
      },
    };

    // Create the item in Firestore first to get an ID. Pass an empty images array for now.
    const createdItem = await addExhibitItem({ ...newItemData, images: [], createdAt: new Date().toISOString() });
    const newItemId = createdItem.id;

    // Upload the image to Cloud Storage using the new ID
    const publicUrl = await uploadImageToStorage(photoDataUri, newItemId, 0);

    // Update the item with the public image URL
    await updateExhibitItem(newItemId, { images: [publicUrl] });
    
    revalidatePath('/');
    revalidatePath(`/items/${newItemId}`);
    return { newItemId: newItemId };

  } catch (error) {
    console.error('Error in analyzeImageAction:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred.';
    return { error: `Failed to analyze image: ${errorMessage}` };
  }
}

export async function getAIChatResponse(itemId: string, history: ChatMessage[]): Promise<ChatMessage> {
    const item = await getExhibitItemById(itemId);
    if (!item) {
        throw new Error("Item not found");
    }

    const userQuery = history.length > 0 ? history[history.length - 1].content : '';
    if (!userQuery) {
        return { role: 'assistant', content: "I'm sorry, I didn't receive a question."};
    }
    const itemDescription = item.description + '\n\n' + JSON.stringify(item.metadata);

    try {
        const result = await chatAboutExhibitContext({
            itemDescription,
            userQuery,
        });

        return {
            role: 'assistant',
            content: result.answer,
        };
    } catch (error) {
        console.error('Error in getAIChatResponse:', error);
        return { role: 'assistant', content: 'There was an issue communicating with the AI. Please try again later.'}
    }
}


export async function updateExhibitItemAction(itemId: string, data: Partial<ExhibitItem>) {
  await updateExhibitItem(itemId, data);
  revalidatePath(`/items/${itemId}`);
  revalidatePath(`/items/${itemId}/chat`);
}

export async function updateImageAction(itemId: string, formData: FormData): Promise<{ newInfoFound: boolean, updatedMetadata?: ExhibitMetadata }> {
  const photoDataUri = formData.get('image-data-uri') as string;
  const item = await getExhibitItemById(itemId);

  if (!photoDataUri) {
    throw new Error('No image file provided.');
  }
  if (!item) {
    throw new Error('Exhibit item not found.');
  }

  const result = await updateExhibitImage({
    newPhotoDataUri: photoDataUri,
    existingMetadata: item.metadata
  });

  // Upload new image to storage first
  const newImageUrl = await uploadImageToStorage(photoDataUri, itemId, item.images.length);
  const updatedImages = [...item.images, newImageUrl];

  if (result.newInfoFound && result.updatedMetadata) {
    const updatedItem: Partial<ExhibitItem> = {
      images: updatedImages,
      metadata: result.updatedMetadata,
      name: result.updatedMetadata.name || item.name,
      description: result.updatedMetadata.description || item.description,
    };
    await updateExhibitItem(itemId, updatedItem);
    revalidatePath(`/items/${itemId}`);
    revalidatePath(`/items/${itemId}/chat`);
    return { newInfoFound: true, updatedMetadata: result.updatedMetadata };
  } else {
    // If user forces add, we just add the image
    const forceAdd = formData.get('force-add') === 'true';
    if (forceAdd) {
        await updateExhibitItem(itemId, { images: updatedImages });
        revalidatePath(`/items/${itemId}`);
        revalidatePath(`/items/${itemId}/chat`);
    }
    return { newInfoFound: false };
  }
}

export async function deleteExhibitItemAction(itemId: string): Promise<{ error?: string }> {
    try {
        getFirebaseAdminApp(); // Ensure admin app is initialized
        const item = await getExhibitItemById(itemId);
        if (item && item.images) {
            const bucket = getStorage().bucket();
            // Delete all images from storage associated with the item
            for (const imageUrl of item.images) {
                try {
                    const url = new URL(imageUrl);
                    const path = url.pathname.substring(1); // remove leading '/'
                    const decodedPath = decodeURIComponent(path.split('/').slice(2).join('/')); // remove bucket name
                    await bucket.file(decodedPath).delete();
                } catch (e) {
                    console.error(`Failed to delete image ${imageUrl} from storage:`, e);
                }
            }
        }
        await deleteExhibitItem(itemId);
        revalidatePath('/');
    } catch (error) {
        console.error("Deletion error:", error);
        return { error: 'Failed to delete item.' };
    }
    redirect('/');
}
